In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 41.1 KB

In [6]:
time .info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 118.7 KB

### Working with Dates

In [7]:
date = date.drop(columns=['product_id', 'city_id', 'orders'])

In [8]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 7.9 KB

In [9]:
# Extract Year
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  date_year
991 2019-01-12       2019
590 2018-08-14       2018
359 2019-03-23       2019
980 2018-08-03       2018
869 2018-12-30       2018

In [10]:
# Extract Months no.
date['date_month_no'] = date['date'].dt.month

date.sample(5)

          date  date_year  date_month_no
309 2019-08-14       2019              8
647 2018-09-05       2018              9
473 2019-05-15       2019              5
562 2018-12-01       2018             12
321 2019-12-04       2019             12

In [11]:
# Extract Month Name
date['date_month_name'] = date['date'].dt.month_name()

date.sample(5)

          date  date_year  date_month_no date_month_name
821 2018-12-07       2018             12        December
790 2019-11-02       2019             11        November
82  2019-10-26       2019             10         October
346 2018-11-10       2018             11        November
895 2018-10-31       2018             10         October

In [12]:
# Extract days
# Extract Months
date['date_day'] = date['date'].dt.day

date.sample(5)

          date  date_year  date_month_no date_month_name  date_day
102 2018-08-30       2018              8          August        30
695 2018-10-01       2018             10         October         1
309 2019-08-14       2019              8          August        14
391 2019-10-21       2019             10         October        21
765 2018-11-01       2018             11        November         1

In [13]:
# Day of week
date['date_DOW'] = date['date'].dt.dayofweek

date.sample(5)

          date  date_year  date_month_no date_month_name  date_day  date_DOW
547 2019-06-21       2019              6            June        21         4
85  2019-11-13       2019             11        November        13         2
288 2019-06-24       2019              6            June        24         0
335 2018-09-05       2018              9       September         5         2
45  2019-07-01       2019              7            July         1         0

In [14]:
# Day of week --> name
date['date_DOW_name'] = date['date'].dt.day_name()

In [15]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_DOW_name'].isin(['Sunday', 'Saturday']), 1,0)

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_DOW,date_DOW_name,date_is_weekend
341,2019-05-04,2019,5,May,4,5,Saturday,1
730,2019-06-22,2019,6,June,22,5,Saturday,1
604,2019-12-05,2019,12,December,5,3,Thursday,0
926,2019-07-07,2019,7,July,7,6,Sunday,1
627,2018-08-01,2018,8,August,1,2,Wednesday,0

In [16]:
# Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_DOW,date_DOW_name,date_is_weekend,date_week
382,2018-09-30,2018,9,September,30,6,Sunday,1,39
177,2019-08-10,2019,8,August,10,5,Saturday,1,32
776,2019-08-18,2019,8,August,18,6,Sunday,1,33
543,2019-12-05,2019,12,December,5,3,Thursday,0,49
455,2018-09-08,2018,9,September,8,5,Saturday,1,36

In [17]:
# Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_DOW,date_DOW_name,date_is_weekend,date_week,quarter
11,2019-08-02,2019,8,August,2,4,Friday,0,31,3
562,2018-12-01,2018,12,December,1,5,Saturday,1,48,4
836,2018-07-17,2018,7,July,17,1,Tuesday,0,29,3
206,2019-04-24,2019,4,April,24,2,Wednesday,0,17,2
325,2019-06-13,2019,6,June,13,3,Thursday,0,24,2

In [18]:
# Extract Semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_DOW,date_DOW_name,date_is_weekend,date_week,quarter,semester
990,2018-10-28,2018,10,October,28,6,Sunday,1,43,4,2
771,2019-06-17,2019,6,June,17,0,Monday,0,25,2,1
55,2019-07-26,2019,7,July,26,4,Friday,0,30,3,2
578,2019-06-28,2019,6,June,28,4,Friday,0,26,2,1
590,2018-08-14,2018,8,August,14,1,Tuesday,0,33,3,2

In [19]:
# Extract Time elapsed Between Dates

import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 24, 17, 55, 59, 70567)

In [20]:
today - date['date']

0     2418 days 17:55:59.070567
1     2900 days 17:55:59.070567
2     2831 days 17:55:59.070567
3     2533 days 17:55:59.070567
4     2756 days 17:55:59.070567
                 ...
995   2846 days 17:55:59.070567
996   2787 days 17:55:59.070567
997   2635 days 17:55:59.070567
998   2700 days 17:55:59.070567
999   2474 days 17:55:59.070567
Name: date, Length: 1000, dtype: timedelta64[us]

In [21]:
# only want days
(today - date['date']).dt.days

0      2418
1      2900
2      2831
3      2533
4      2756
       ...
995    2846
996    2787
997    2635
998    2700
999    2474
Name: date, Length: 1000, dtype: int64

In [22]:
# months passed
(
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)

0      79
1      95
2      93
3      83
4      90
       ..
995    93
996    91
997    86
998    88
999    81
Name: date, Length: 1000, dtype: int32

### Working with Time dataset

In [23]:
time = time.drop(columns=['msg'])

In [24]:
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00

In [25]:
# converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 7.9 KB

In [27]:
time['time'] = time['date'].dt.time
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.sample(5)

                   date  hour  min  sec      time
649 2013-02-22 23:18:00    23   18    0  23:18:00
167 2014-04-29 00:55:00     0   55    0  00:55:00
780 2012-11-29 01:52:00     1   52    0  01:52:00
492 2014-07-17 00:46:00     0   46    0  00:46:00
986 2013-06-02 00:18:00     0   18    0  00:18:00

In [28]:
# Time difference

today - time['date']

0     4604 days 17:05:59.070567
1     4468 days 18:15:59.070567
2     4954 days 17:34:59.070567
3     4256 days 17:24:59.070567
4     4653 days 18:44:59.070567
                 ...
995   5243 days 17:05:59.070567
996   4564 days 18:41:59.070567
997   5029 days 18:18:59.070567
998   5145 days 18:21:59.070567
999   4417 days 18:30:59.070567
Name: date, Length: 1000, dtype: timedelta64[us]

In [29]:
(today - time['date'])/np.timedelta64(1, 's')

0      3.978472e+08
1      3.861010e+08
2      4.280889e+08
3      3.677811e+08
4      4.020867e+08
           ...
995    4.530568e+08
996    3.943969e+08
997    4.345715e+08
998    4.445941e+08
999    3.816955e+08
Name: date, Length: 1000, dtype: float64

In [30]:
(today - time['date'])/np.timedelta64(1, 'h')

0      110513.099742
1      107250.266408
2      118913.583075
3      102161.416408
4      111690.749742
           ...
995    125849.099742
996    109554.699742
997    120714.316408
998    123498.366408
999    106026.516408
Name: date, Length: 1000, dtype: float64

In [31]:
(today - time['date'])/np.timedelta64(1, 'm')

0      6.630786e+06
1      6.435016e+06
2      7.134815e+06
3      6.129685e+06
4      6.701445e+06
           ...
995    7.550946e+06
996    6.573282e+06
997    7.242859e+06
998    7.409902e+06
999    6.361591e+06
Name: date, Length: 1000, dtype: float64