In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [13]:
df = pd.read_csv(
    r"C:\Users\praja\OneDrive\Codes_Project\Data_Science\Machine Learning\Data Preprocessing\Feature Engineering\Feature Transformation\Imputation\Univariate Handling\Titanic.csv")[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]


df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [14]:
df.dropna(inplace=True)

In [15]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [19]:
X = df[['Age', 'Pclass', 'SibSp', 'Parch']]
y = df['Survived']

In [20]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [21]:
np.mean(cross_val_score(LogisticRegression(), X,y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

### Applying Feature Constuction

In [22]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [23]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [27]:
def myfunc(num):
    if num == 1:
        # alone 
        return 0
    elif num > 1 and num <= 4:
        # small family
        return 1
    else:
        # large Famliy
        return 2

In [28]:
myfunc(4)

1

In [30]:
X['Family_type'] = X['Family_size'].apply(myfunc)
X.sample(5)

      Age  Pclass  SibSp  Parch  Family_size  Family_type
265  36.0       2      0      0            0            2
456  65.0       1      0      0            0            2
864  24.0       2      0      0            0            2
677  18.0       3      0      0            0            2
314  43.0       2      1      1            1            0

In [34]:
X.drop(columns=['SibSp', 'Parch', 'Family_size'], inplace=True)

In [35]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            0
1  38.0       1            0
2  26.0       3            2
3  35.0       1            0
4  35.0       3            2

In [36]:
np.mean(cross_val_score(LogisticRegression(), X,y, scoring='accuracy', cv=20))

np.float64(0.7312698412698414)

### Feature Splitting

In [37]:
df2 = pd.read_csv(
    r"C:\Users\praja\OneDrive\Codes_Project\Data_Science\Machine Learning\Data Preprocessing\Feature Engineering\Feature Transformation\Imputation\Univariate Handling\Titanic.csv")


df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
df2['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [39]:
df2['Title'] = df2['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [40]:
df2[['Title', 'Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [43]:
df2.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [44]:
df2['Is_Married'] = 0
df2['Is_Married'].loc[df2['Title'] == 'Mrs'] = 1

C:\Users\praja\AppData\Local\Temp\ipykernel_15036\359320749.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df2['Is_Married'].loc[df2['Title'] == 'Mrs'] = 1

In [45]:
df2['Is_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64